### ISSUE TITLE
Count issue

### ISSUE THREAD

**Issue by MarieLambois** [Geomatys/constellation#10]
Hello,

We have installed 1.1.2 version of constellation at this address:
https://dgiwg.ign.fr/constellation

When we connect to the administration plateform we get the following message:
![capture](https://cloud.githubusercontent.com/assets/12797943/13105654/95f798f4-d564-11e5-88cf-3fc9c8f529f6.JPG)

and then we cannot access to anything...

"constellation" database has been created on Postgres. There does not seem to be any specific information in the log files. 

Have you got an idea on where this issue comes from ?

**Comment by msidhoum** [comment]
Hi @MarieLambois 

First of all thank you for your contribution.
I noticed that you use an old version of tomcat (7.0.28), it is recommended to use Apache Tomcat 7.0.47+ with support of websockets

According to the README 

> => Prerequires
To run Constellation-SDI, you'll need :
    JDK7u45+ from Oracle.
    PostgreSQL 9.x
    Apache Tomcat 7.0.47+ with support of websockets 

try to upgrade tomcat, you can download it here http://archive.apache.org/dist/tomcat/tomcat-7/v7.0.68/bin/apache-tomcat-7.0.68.zip

if this does not work then make sure your apache configuration is correctly defined, 
it should look like this

`<VirtualHost *:80>`
`   ProxyPreserveHost Off`
`   ProxyPass         /constellation/ http://localhost:8080/constellation/`
`   ProxyPassReverse  /constellation/ http://localhost:8080/constellation/`
`   ProxyPassReverseCookiePath /constellation /constellation`
`   ServerName dgiwg.ign.fr`
`</VirtualHost>`


Make sure the variable -Dcstl.url is defined in your tomcat/bin/setenv.sh file like this
`JAVA_OPTS="$JAVA_OPTS -Dcstl.url=https://dgiwg.ign.fr/constellation/"`

Can you send us the tomcat server startup logs ?

Best Regards.

**Comment by msidhoum** [comment]
BTW note there is a new release of Constellation-SDI version 1.1.3 
http://constellation-sdi.org/en/downloads.html

Once your application is functional please change the password of your user account to have better secure application. you can change the password by opening the "My account" page.

Best regards.

**Comment by MarieLambois** [comment]
Thanks for your help it works ! 

The tomcat version was wrong indeed. I just checked that I had a tomcat 7 and did not check the sub sub versions... 

Maybe you could add a WARn in the logs, checking the tomcat version installed. (BTW it is nice that the log levels are in color)

Thanks again

Marie
