### ISSUE TITLE
Constellation Installation

### ISSUE THREAD

**Issue by jschaeff** [Geomatys/constellation#4]
Hi,

I would like to give constellation a try. But I could not compete the mvn install.
I also tried to put the .war in a tomcat7 engine but it seems that it's not dedigned to run inside tomcat.
I was unable to find any documentation anywhere.
Could you help me deploy it ?

My environment is Debian Stable, Oracke Java7.
I cloned the repository and ran : 

  JAVA_HOME=/usr/lib/jvm/java-7-oracle mvn install

There is an error in the tests :

testSOSGetCapabilities(org.constellation.ws.embedded.SOSSoapRequestTest)  Time elapsed: 10311 sec  <<< FAILURE!
java.lang.AssertionError: Expected textContent "gml:Envelope" but got "ns16:Envelope" for nodes:
Expected node: #text="gml:Envelope"
Actual node:   #text="ns16:Envelope"

Thank you for your help !

**Comment by glegal** [comment]
try to build without excuting the test : mvn clean install -DskipTests

**Comment by qboileau** [comment]
Hi @jschaeff , we are aware that some tests in embedded module fail and we are currently working to fix them. 
As @glegal suggest, you can build Constellation with -DskipTests option for now. 
When Constellation is fully built, you may deploy the **constellation.war** located in **constellation/modules/cstl-sdi/target** folder in your tomcat7. 

Or you can download the latest Constellation builded war in our CI on [http://constellation-sdi.org/en/index.html](http://constellation-sdi.org/en/index.html)

**Comment by jschaeff** [comment]
Thanks for your help.
I tried the nightly war file in tomcat7 with oracle java7.
There is an error at deployment, here it says : 

````
[DEBUG] org.constellation.admin.conf.AsyncConfiguration - Creating Async Task Executor
Wed Feb 18 16:36:04 CET 2015 Thread[localhost-startStop-1,5,main] java.io.FileNotFoundException: derby.log (Permission non accordée)
[ERROR] org.springframework.web.context.ContextLoader - Context initialization failed
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'com.ryantenney.metrics.spring.config.annotation.DelegatingMetricsC
onfiguration': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire
 method: public void com.ryantenney.metrics.spring.config.annotation.DelegatingMetricsConfiguration.setMetricsConfigurers(java.util.List); nested exceptio
n is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'metricsConfiguration': Injection of autowired dependencies fa
iled; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire field: private javax.sql.DataSource org.constellatio
n.conf.MetricsConfiguration.dataSource; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'dataSo
urce' defined in class path resource [cstl/spring/cstl-ds.xml]: Instantiation of bean failed; nested exception is org.springframework.beans.factory.BeanDe
finitionStoreException: Factory method [public static javax.sql.DataSource org.constellation.admin.EmbeddedDatabase.getOrCreateDataSource() throws java.sq
l.SQLException] threw exception; nested exception is java.lang.ExceptionInInitializerError
````
I guess, derby.log should get in some path and tha tomcat7 is not able to create it. But I don't know where that would be.

**Comment by qboileau** [comment]
The **derby.log** file is created by Derby on the directory from where tomcat is started.
For example if tomcat is located on **/opt/apache-tomcat/** and runned like this :
`cd /opt/apache-tomcat/bin && ./catalina.sh start`
In that case **derby.log** file should be created on **/opt/apache-tomcat/bin/** folder.

I think that running Tomcat from a directory owned by the user that start Tomcat should resolve your problem. Otherwise, could you attach the full Tomcat catalina\*.log and localhost\*.log log files ?
