### ISSUE TITLE
Feature info encoding for text/html info_format

### ISSUE THREAD

**Issue by fredmorin** [Geomatys/constellation#8]
I noticed encoding problems with GetFeatureInfo on WMS services in text/html info_format.

To reproduce:
- Load the "bornes-fontaines" shapefile available on the Ville de Québec open data portal http://donnees.ville.quebec.qc.ca/donne_details.aspx?jdid=28
- Create a wms service to expose the data
- Execute the following request:
  http://constellation:8080/constellation/WS/wms/bornes?SERVICE=WMS&VERSION=1.1.1&REQUEST=GetFeatureInfo&BBOX=-71.33506514475558902,46.71846952726378532,-71.15012951657743656,46.99752418049688885&SRS=EPSG:4326&WIDTH=560&HEIGHT=845&LAYERS=BORNE&STYLES=&&QUERY_LAYERS=BORNE&INFO_FORMAT=text/html&X=162&Y=359&FEATURE_COUNT=10
- Notice encoding errors with french characters É é

**Comment by msidhoum** [comment]
Hi, try to encode the shapefile in UTF-8
to carry out that, try with ogr2ogr tool or qgis to rewriter your shapefile
see this page
http://gis.stackexchange.com/questions/15912/how-to-encode-shapefiles-from-latin1-to-utf-8

**Comment by desruisseaux** [comment]
This project is archived and replaced by [Examind-community](https://github.com/Geomatys/examind-community).
