### ISSUE TITLE
WMS Layer SRS

### ISSUE THREAD

**Issue by fredmorin** [Geomatys/constellation#9]
WMS Services support a list of srs by default including the popular 4326 and 3857, but also some srs specific to France. Could you provide some documentation regarding the configuration of supported WMS srs? For example, EPSG:32198 for Québec.

Supported SRS by constellation wms services out of the box:
      <SRS>EPSG:4326</SRS>
      <SRS>CRS:84</SRS>
      <SRS>EPSG:3395</SRS>
      <SRS>EPSG:3857</SRS>
      <SRS>EPSG:27571</SRS>
      <SRS>EPSG:27572</SRS>
      <SRS>EPSG:27573</SRS>
      <SRS>EPSG:27574</SRS>

**Comment by mackristof** [comment]
Hi @fredmorin,
getCapabiliities from WMS response contains only default SRS defined here : https://github.com/Geomatys/constellation/blob/master/modules/library/api/src/main/java/org/constellation/api/CommonConstants.java

but you can make getMap request with major SRS defined in EPSG database : http://www.geotoolkit.org/modules/referencing/

**Comment by desruisseaux** [comment]
This project is archived and replaced by [Examind-community](https://github.com/Geomatys/examind-community).
